export const whatsappChatList = [
  {
    contactName: "John Doe",
    lastMessage: "Hi there!",
    timestamp: "10:30 AM",
    unreadCount: 2,
    avatar: "john-avatar.jpg",
  },
  {
    contactName: "Alice Smith",
    lastMessage: "Hello!",
    timestamp: "Yesterday",
    unreadCount: 0,
    avatar: "alice-avatar.jpg",
  },
  {
    contactName: "Bob Johnson",
    lastMessage: "What are you up to?",
    timestamp: "Monday",
    unreadCount: 1,
    avatar: "bob-avatar.jpg",
  },
  {
    contactName: "Emily Brown",
    lastMessage: "See you later!",
    timestamp: "Sunday",
    unreadCount: 0,
    avatar: "emily-avatar.jpg",
  },
  {
    contactName: "Michael Wilson",
    lastMessage: "Good morning!",
    timestamp: "Sunday",
    unreadCount: 3,
    avatar: "michael-avatar.jpg",
  },
  {
    contactName: "Sophia Davis",
    lastMessage: "Sure thing!",
    timestamp: "Saturday",
    unreadCount: 0,
    avatar: "sophia-avatar.jpg",
  },
  {
    contactName: "Daniel Lee",
    lastMessage: "I'm on my way.",
    timestamp: "Saturday",
    unreadCount: 2,
    avatar: "daniel-avatar.jpg",
  },
  {
    contactName: "Olivia Martinez",
    lastMessage: "Thanks a lot!",
    timestamp: "Friday",
    unreadCount: 0,
    avatar: "olivia-avatar.jpg",
  },
  {
    contactName: "James Garcia",
    lastMessage: "Happy birthday!",
    timestamp: "Friday",
    unreadCount: 1,
    avatar: "james-avatar.jpg",
  },
  {
    contactName: "Ava Hernandez",
    lastMessage: "Let's meet up!",
    timestamp: "Thursday",
    unreadCount: 0,
    avatar: "ava-avatar.jpg",
  },{
    contactName: "John Doe",
    lastMessage: "Hi there!",
    timestamp: "10:30 AM",
    unreadCount: 2,
    avatar: "john-avatar.jpg",
  },
  {
    contactName: "Alice Smith",
    lastMessage: "Hello!",
    timestamp: "Yesterday",
    unreadCount: 0,
    avatar: "alice-avatar.jpg",
  },
  {
    contactName: "Bob Johnson",
    lastMessage: "What are you up to?",
    timestamp: "Monday",
    unreadCount: 1,
    avatar: "bob-avatar.jpg",
  },
  {
    contactName: "Emily Brown",
    lastMessage: "See you later!",
    timestamp: "Sunday",
    unreadCount: 0,
    avatar: "emily-avatar.jpg",
  },
  {
    contactName: "Michael Wilson",
    lastMessage: "Good morning!",
    timestamp: "Sunday",
    unreadCount: 3,
    avatar: "michael-avatar.jpg",
  },
  {
    contactName: "Sophia Davis",
    lastMessage: "Sure thing!",
    timestamp: "Saturday",
    unreadCount: 0,
    avatar: "sophia-avatar.jpg",
  },
  {
    contactName: "Daniel Lee",
    lastMessage: "I'm on my way.",
    timestamp: "Saturday",
    unreadCount: 2,
    avatar: "daniel-avatar.jpg",
  },
  {
    contactName: "Olivia Martinez",
    lastMessage: "Thanks a lot!",
    timestamp: "Friday",
    unreadCount: 0,
    avatar: "olivia-avatar.jpg",
  },
  {
    contactName: "James Garcia",
    lastMessage: "Happy birthday!",
    timestamp: "Friday",
    unreadCount: 1,
    avatar: "james-avatar.jpg",
  },
  {
    contactName: "Ava Hernandez",
    lastMessage: "Let's meet up!",
    timestamp: "Thursday",
    unreadCount: 0,
    avatar: "ava-avatar.jpg",
  },
  // 20 additional contacts
  {
    contactName: "Ella Davis",
    lastMessage: "I'll be there soon.",
    timestamp: "Thursday",
    unreadCount: 2,
    avatar: "ella-avatar.jpg",
  },
  {
    contactName: "Liam Johnson",
    lastMessage: "How's it going?",
    timestamp: "Wednesday",
    unreadCount: 1,
    avatar: "liam-avatar.jpg",
  },
  {
    contactName: "Mia Thompson",
    lastMessage: "Busy day today!",
    timestamp: "Wednesday",
    unreadCount: 0,
    avatar: "mia-avatar.jpg",
  },
  {
    contactName: "Noah Wilson",
    lastMessage: "See you in a bit!",
    timestamp: "Tuesday",
    unreadCount: 0,
    avatar: "noah-avatar.jpg",
  },
  {
    contactName: "Ava Brown",
    lastMessage: "Don't forget to call.",
    timestamp: "Tuesday",
    unreadCount: 1,
    avatar: "ava-avatar.jpg",
  },
  {
    contactName: "Sophia Harris",
    lastMessage: "Missing you!",
    timestamp: "Monday",
    unreadCount: 0,
    avatar: "sophia-avatar.jpg",
  },
  {
    contactName: "Liam White",
    lastMessage: "Let's grab lunch.",
    timestamp: "Sunday",
    unreadCount: 2,
    avatar: "liam-avatar.jpg",
  },
  {
    contactName: "Aiden Smith",
    lastMessage: "I need your help.",
    timestamp: "Saturday",
    unreadCount: 1,
    avatar: "aiden-avatar.jpg",
  },
  {
    contactName: "Lucas Taylor",
    lastMessage: "What's up?",
    timestamp: "Friday",
    unreadCount: 0,
    avatar: "lucas-avatar.jpg",
  },
  {
    contactName: "Emma Miller",
    lastMessage: "See you at the party!",
    timestamp: "Thursday",
    unreadCount: 1,
    avatar: "emma-avatar.jpg",
  },
];
